name: 'Microsoft Teams Notification'
description: ''

inputs:
  service:
    description: 'The name of the service'
    required: true
  state:
    description: 'The current state of the service (Started, Failed, Success)'
    required: true
    default: "Started"
  stage:
    description: 'The deployment stage (development, acceptance, production)'
    required: true
  brand:
    description: 'The brand which is affected (Microspot, Interdiscount)'
    required: true
  version:
    description: 'The deployment version'
    required: true
  webhook:
    description: 'The webhook uri'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up git config and update versions in helm chart files
      run: |
        echo "::set-env name=BRAND_IMAGE_URL::https://www.microspot.ch/images/logos/Microspot_logo.png"
        echo "::set-env name=COLOR::49C6e5"
        echo "::set-env name=NOW::$(date +'%d.%m.%Y %H:%M:%S')"

        curl --request POST \
        --url ${{ inputs.webhook }} \
        --header 'content-type: application/json' \
        --data '{"@type": "MessageCard", "@context": "https://schema.org/extensions", "summary": "${{ inputs.state }}: Deployment to ${{ inputs.brand }} ${{ inputs.stage }}", "themeColor": "${{ env.COLOR }}", "title": "${{ inputs.state }}: Deployment to ${{ inputs.brand }} ${{ inputs.stage }}", "sections": [ { "activityTitle": "${{ inputs.version }}", "activitySubtitle": "${{ env.NOW }}", "activityImage": "${{ env.BRAND_IMAGE_URL }}", "facts": [ { "name": "Service", "value": "${{ inputs.service }}" } ] } ], }'
      shell: bash
