name: 'Microsoft Teams Notification'
description: ''

inputs:
  service:
    description: 'The name of the service'
    required: true
  state:
    description: 'The current state of the service (Started, Failed, Success)'
    required: true
    default: "Started"
  stage:
    description: 'The deployment stage (development, acceptance, production)'
    required: true
  brand:
    description: 'The brand which is affected (Microspot, Interdiscount)'
    required: true
  version:
    description: 'The deployment version'
    required: true
  webhook:
    description: 'The webhook uri'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up git config and update versions in helm chart files
      run: |

        if ${{ inputs.brand  == 'interdiscount' || inputs.brand  == 'Interdiscount' || inputs.brand  == 'Interdiscount' || inputs.brand  == 'id'  || inputs.brand  == 'ID' || inputs.brand  == 'Id' }} then
          echo "::set-env name=BRAND_IMAGE_URL::https://media.glassdoor.com/sqll/158689/interdiscount-squarelogo-1472471988427.png"
        else
          echo "::set-env name=BRAND_IMAGE_URL::https://www.microspot.ch/images/logos/Microspot_logo.png"
        fi

        if ${{ inputs.state  == 'Success' || inputs.brand  == 'success' }} then
          echo "::set-env name=COLOR::00ae6d"
        else if ${{ inputs.state  == 'Failed' || inputs.brand  == 'failed' }} then
          echo "::set-env name=COLOR::e20713"
        else
          echo "::set-env name=COLOR::49C6e5"
        fi

        echo "::set-env name=NOW::$(date +'%d.%m.%Y %H:%M:%S')"
        echo "::set-env name=TEXT::${{ inputs.state }}: Deployment to ${{ inputs.brand }} ${{ inputs.stage }}"

        curl --request POST \
        --url ${{ inputs.webhook }} \
        --header 'content-type: application/json' \
        --data '{"@type": "MessageCard", "@context": "https://schema.org/extensions", "summary": "$TEXT", "themeColor": "$COLOR", "title": "$TEXT", "sections": [ { "activityTitle": "${{ inputs.version }}", "activitySubtitle": "$NOW", "activityImage": "$BRAND_IMAGE_URL", "facts": [ { "name": "Service", "value": "${{ inputs.service }}" } ] } ], }'
      shell: bash